name: Freenet Raven
version: 0.0.1
slug: freenet-raven
image: ghcr.io/HeyITGuyFixIt/homeassistant-app-freenet-raven-{arch}
description: Decentralized Twitter/X-like application built on Freenet
url: https://github.com/HeyITGuyFixIt/Freenet-HomeAssistant-Apps
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: "mdi:bird"
panel_title: "Raven"
services:
  - "freenet:need"
schema:
  peer_host: str
  peer_port: port
options:
  peer_host: "core-freenet"
  peer_port: 9798