name: Freenet Harvest
version: 0.0.1
slug: freenet-harvest
description: Decentralized marketplace for Freenet
url: https://github.com/HeyITGuyFixIt/Freenet-HomeAssistant-Apps
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: "mdi:barley"
panel_title: "Harvest"
services:
  - "freenet:need"
schema:
  peer_host: str
  peer_port: port
options:
  peer_host: "core-freenet"
  peer_port: 9798