#!/bin/bash
set -euo pipefail
export HOME=/data

# Validate config first
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

exec caddy run \
  --config /etc/caddy/Caddyfile \
  --adapter caddyfile
