name: Freenet Mail
version: 0.0.1
slug: freenet-mail
image: ghcr.io/HeyITGuyFixIt/homeassistant-app-freenet-mail-{arch}
description: Decentralized email application built on Freenet
url: https://github.com/HeyITGuyFixIt/Freenet-HomeAssistant-Apps
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: "mdi:email"
panel_title: "Mail"
services:
  - "freenet:need"
schema:
  peer_host: str
  peer_port: port
options:
  peer_host: "core-freenet"
  peer_port: 9798