name: Freenet Delta
version: 0.0.1
slug: freenet-delta
description: Decentralized website builder on Freenet
url: https://github.com/HeyITGuyFixIt/homeassistant-addons
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: "mdi:delta"
panel_title: "Delta"
services:
  - "freenet:need"
schema:
  peer_host: str
  peer_port: port
options:
  peer_host: "core-freenet"
  peer_port: 9798